version: '3'

services:
 web:
  image: nginx:alpine
  ports:
   - 80:80
  volumes:
   - ./code:/public_html
   - ./conf.d:/etc/nginx/conf.d/default.conf
  networks:
   - nginxphp

 php:
  image: webdevops/php:7.4-alpine
  volumes:
   - ./code:/public_html
  expose:
   - 9000
  networks:
   - nginxphp

networks:
 nginxphp:
